cursor #cdd6f4
cursor_text_color #a6adc8

foreground            #cdd6f4
background            #1e1e2e
selection_foreground  #1e1e2e
selection_background  #74c7ec
url_color             #89dceb

color0   #181825
color1   #ff72a2
color2   #75eb80
color3   #fff572
color4   #6fcedf
color5   #19606c
color6   #89dceb
color7   #e7f4f6
color8   #8d9798
color9   #ff9fc0
color10  #a5ffae
color11  #fff8a5
color12  #a4f1ff
color13  #b4f3ff
color14  #cff7ff
color15  #f8feff
